export const ARTICLE_MAX_LENGTH = 100;
export const ARTICLE_DESCRIPTION_MAX_LENGTH = 250;
export const ARTICLE_BODY_MAX_LENGTH = 10000;
export const ARTICLE_COVER_IMAGE_MAX_LENGTH = 200;

export const FIND_MANY_ARTICLES_QUERY_DTO_DEFAULT_LIMIT = 20;
export const FIND_MANY_ARTICLES_QUERY_DTO_DEFAULT_OFFSET = 0;
