import { ArticleListItem } from "@/interfaces/article.interface";

export const articleList: ArticleListItem[] = [
    {
      title: "The furture of UI/UX Design",
      slug: "the-future-of-ui-ux-design",
      description: "An in-depth look at the future of UI/UX design.",
      status: "Published",
      cover_image: "/mock_cover_image.avif",
      author: {
        name: "John Doe",
        image: "",
        username: "johndoe",
      },
      comments_count: 12,
      views: 1500,
      reading_time: 8,
      favorite_count: 45,
      tagList: ["Design", "UI/UX", "Future"],
      published_at: "2024-04-20",
      created_at: "2024-04-15",
      updated_at: "2024-04-20",
    },
    {
      title: "Getting Started with TypeScript",
      slug: "getting-started-with-typescript",
      description: "A beginner's guide to TypeScript.",
      status: "Draft",
      cover_image: "",
      author: {
        name: "Jane Smith",
        image: "",
        username: "janesmith",
      },
      comments_count: 0,
      views: 0,
      reading_time: 3,
      favorite_count: 0,
      tagList: ["Testing", "Drafts"],
      created_at: "2024-04-10",
      published_at: "",
      updated_at: "2024-04-18",
    },
    {
      title: "10 tips for effective remote work",
      slug: "10-tips-for-effective-remote-work",
      description: "Maximize your productivity while working remotely.",
      cover_image: "",
      author: {
        name: "Mike Johnson",
        image: "",
        username: "mikejohnson",
      },
      comments_count: 0,
      views: 0,
      reading_time: 5,
      favorite_count: 0,
      status: "Rejected",
      tagList: ["Remote Work", "Productivity"],
      created_at: "2024-04-12",
      published_at: "",
      updated_at: "2024-04-18",
    },
    {
      title: "AI in Modern Web Development",
      slug: "ai-in-modern-web-development",
      description:
        "Exploring the role of AI in today's web development landscape.",
      status: "Pending",
      cover_image: "",
      author: {
        name: "Jane Smith",
        image: "",
        username: "janesmith",
      },
      comments_count: 0,
      views: 0,
      reading_time: 7,
      favorite_count: 0,
      tagList: ["AI", "Web Development"],
      created_at: "2024-04-14",
      published_at: "",
      updated_at: "2024-04-18",
    },
  ];
